# Generated by Django 2.2.9 on 2019-12-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True)),
                ('tweet_id', models.CharField(max_length=20)),
                ('option', models.CharField(choices=[(1, 'option_1'), (2, 'option_2'), (3, 'option_3')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TweetOption',
                'verbose_name_plural': 'TweetOptions',
                'unique_together': {('user_id', 'tweet_id', 'option')},
            },
        ),
    ]
