# Generated by Django 2.2.9 on 2019-12-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tweetoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetoption',
            name='user_id',
            field=models.CharField(max_length=32),
        ),
    ]
