# Generated by Django 2.2.9 on 2019-12-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191229_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweetoption',
            unique_together={('user_id', 'tweet_id')},
        ),
    ]
